pipeline {
    agent any

    environment {
        // Renamed to your naming preference
        IMAGE_NAME = "gunjan-django-app"
        IMAGE_TAG  = "${BUILD_NUMBER}"
        // Matches Abhishek's repository folder structure exactly
        SUB_DIR    = "python-jenkins-argocd-k8s" 
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }
           stage('Debug Folder Structure') {
                steps {
                    echo "=== PRINTING ALL FILES IN YOUR REPOSITORY ==="
                    // This command lists every single folder and file in your workspace
                    sh "ls -R"
                    echo "============================================="
                }
            }
            stage('Build Local Docker Image') {
                steps {
                   dir("${SUB_DIR}") {
                        // Builds the image locally on your Jenkins server
                        sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                    }
                }
            }
            post {
            success { 
                echo "Successfully built local image -> ${IMAGE_NAME}:${IMAGE_TAG}" 
            }
            failure { 
                echo "Pipeline failed. Check logs." 
            }
        }
    }
}    
    
